<?php

namespace Tests\Feature;

use App\Models\User;
use Database\Seeders\RoleSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

class WorkerTaskTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();
        // Seed roles
        $this->seed(RoleSeeder::class);
    }

    public function test_worker_can_view_assigned_tasks()
    {
        $worker = User::factory()->create([
            'role_id' => 2,
            'estado' => 'activo',
        ]);

        $adminId = User::factory()->create(['role_id' => 1])->id;

        $id_tarea = DB::table('tarea')->insertGetId([
            'nombre' => 'Cosechar Lote A',
            'descripcion' => 'Recolección de café maduro',
            'estado' => 'pendiente',
            'prioridad' => 'alta',
            'creada_por' => $adminId,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('asignacion_tarea')->insert([
            'tarea_id' => $id_tarea,
            'user_id' => $worker->id,
            'fecha_asignacion' => now(),
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $response = $this->actingAs($worker)->get(route('trabajador.tareas'));

        $response->assertStatus(200);
        $response->assertViewIs('trabajador.tareas.index');
        $response->assertViewHasAll(['tareas', 'total', 'pendientes', 'proceso', 'finalizadas']);
        $response->assertSee('Recolección de café maduro');
    }

    public function test_worker_can_start_task()
    {
        $worker = User::factory()->create([
            'role_id' => 2,
            'estado' => 'activo',
        ]);

        $adminId = User::factory()->create(['role_id' => 1])->id;

        $id_tarea = DB::table('tarea')->insertGetId([
            'nombre' => 'Cosechar Lote A',
            'descripcion' => 'Recolección de café maduro',
            'estado' => 'pendiente',
            'prioridad' => 'alta',
            'creada_por' => $adminId,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('asignacion_tarea')->insert([
            'tarea_id' => $id_tarea,
            'user_id' => $worker->id,
            'fecha_asignacion' => now(),
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $response = $this->actingAs($worker)->patch(route('trabajador.tareas.start', $id_tarea));

        $response->assertRedirect();

        // Check state updated to en_progreso
        $this->assertDatabaseHas('tarea', [
            'id' => $id_tarea,
            'estado' => 'en_progreso',
        ]);
    }

    public function test_worker_can_complete_task_with_evidence()
    {
        $worker = User::factory()->create([
            'role_id' => 2,
            'estado' => 'activo',
        ]);

        $adminId = User::factory()->create(['role_id' => 1])->id;

        $id_tarea = DB::table('tarea')->insertGetId([
            'nombre' => 'Cosechar Lote A',
            'descripcion' => 'Recolección de café maduro',
            'estado' => 'en_progreso',
            'prioridad' => 'alta',
            'creada_por' => $adminId,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('asignacion_tarea')->insert([
            'tarea_id' => $id_tarea,
            'user_id' => $worker->id,
            'fecha_asignacion' => now(),
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // Fake the public storage to prevent actual file leftovers
        Storage::fake('public');
        $fakeFile = UploadedFile::fake()->create('evidencia.png', 100); // 100kb

        $response = $this->actingAs($worker)->post(route('trabajador.tareas.complete', $id_tarea), [
            'comentario' => 'Lote completamente cosechado y limpio.',
            'evidencia' => $fakeFile,
        ]);

        $response->assertRedirect();
        $response->assertSessionHas('alert');

        // Check state updated to completada
        $this->assertDatabaseHas('tarea', [
            'id' => $id_tarea,
            'estado' => 'completada',
        ]);

        // Check evidence inserted
        $this->assertDatabaseHas('evidencia_tarea', [
            'tarea_id' => $id_tarea,
            'user_id' => $worker->id,
            'descripcion' => 'Lote completamente cosechado y limpio.',
            'tipo' => 'foto',
        ]);

        // Clean up the public file generated by $file->move in test environment
        $evidenciasDir = public_path('uploads/evidencias');
        if (file_exists($evidenciasDir)) {
            $files = glob($evidenciasDir . '/evidencia_' . $worker->id . '_*');
            foreach ($files as $file) {
                if (is_file($file)) {
                    unlink($file);
                }
            }
        }
    }

    public function test_worker_can_view_task_history_with_date_filters()
    {
        $worker = User::factory()->create([
            'role_id' => 2,
            'estado' => 'activo',
        ]);

        $adminId = User::factory()->create(['role_id' => 1])->id;

        // Create tasks assigned at different dates
        $tareaId1 = DB::table('tarea')->insertGetId([
            'nombre' => 'Tarea Antigua',
            'descripcion' => 'Descripción antigua',
            'estado' => 'completada',
            'prioridad' => 'media',
            'creada_por' => $adminId,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('asignacion_tarea')->insert([
            'tarea_id' => $tareaId1,
            'user_id' => $worker->id,
            'fecha_asignacion' => '2026-08-01',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $tareaId2 = DB::table('tarea')->insertGetId([
            'nombre' => 'Tarea Reciente',
            'descripcion' => 'Descripción reciente',
            'estado' => 'pendiente',
            'prioridad' => 'alta',
            'creada_por' => $adminId,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('asignacion_tarea')->insert([
            'tarea_id' => $tareaId2,
            'user_id' => $worker->id,
            'fecha_asignacion' => '2026-08-15',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // Request history without filters
        $response = $this->actingAs($worker)->get(route('trabajador.historial'));
        $response->assertStatus(200);
        $response->assertViewHas('totalHistorial', 2);

        // Filter: Desde '2026-08-10'
        $responseFiltered = $this->actingAs($worker)->get(route('trabajador.historial', [
            'desde' => '2026-08-10',
        ]));
        $responseFiltered->assertStatus(200);
        $responseFiltered->assertViewHas('totalHistorial', 1);
        $responseFiltered->assertSee('Descripción reciente');
        $responseFiltered->assertDontSee('Descripción antigua');
    }
}
